### ISSUE TITLE
Getting no data

### ISSUE THREAD

**Issue by hamshiva** [projectkk2glider/APM-Mavlink-to-FrSky#4]
Hi,

This project seems really great, it seems that the original project is dead (and wont compile in fact), I hope your fork is alive.
Running this on an Arduino nano I'm unable to get anything else than the flight mode on my Taranis. All other data are zeros ... 

The receiver is a D8R-XP.
The APM is a 2.6 with ArduCopter 3.2.1

Since the flight mode works the wiring do not seems to be the problem.

Do you have any idea what could be wrong ?

**Comment by projectkk2glider** [comment]
My fork relies on APM to send mavlink messages without the arduino asking for them. Check your APM settings that control which mavlink messages are sent.

**Comment by hamshiva** [comment]
Ok thanks for the advice. I tuned param SR1_PARAMS and that is way better.
But it seems that I still missing battery voltage.

**Comment by projectkk2glider** [comment]
My setup:

```
SR1_EXTRA1,2
SR1_EXTRA2,2
SR1_EXTRA3,2
SR1_EXT_STAT,2
SR1_PARAMS,0
SR1_POSITION,2
SR1_RAW_CTRL,2
SR1_RAW_SENS,2
SR1_RC_CHAN,2
```

For battery voltage you first need APM power module. Do you see the battery voltage in APM planner? 

Whis verson of OpenTX are you running on Taranis?

**Comment by hamshiva** [comment]
Ok in fact I have a value for the VFAS (ID 39 nothing on 3B) but only after the APM being ARMED and the value seems strange to me (3.6V). APM planner is reporting the correct value (~11.6V 3S not fully charged pack).
I'm using OpenTX 2.1.1.

**Comment by projectkk2glider** [comment]
Something is strange, I have the value always. Have you played with the opentx sensor ratio parameter? It should be set to -.

**Comment by hamshiva** [comment]
Nope. The ratio is set to -. An other point is that since the APM has been ARMED one time, the value is still there even when then DISARMED.

**Comment by projectkk2glider** [comment]
Are you compiling this project yourself? Because the binaries included here are still old and don't have my changes. Yous should load https://github.com/projectkk2glider/APM-Mavlink-to-FrSky/blob/master/APM_Mavlink_to_FrSky/APM_Mavlink_to_FrSky.ino into Arduion ide and compile it yourself.

**Comment by hamshiva** [comment]
That what I've done as I'm uploading it on an Arduino nano. 
Is there anyway to debug what is going on ?

**Comment by projectkk2glider** [comment]
Sorry, I can't devote more time to this project at this time. You will have to figure this one out for yourself. 

Concerning the VFAS value itself, the Arduino will always send the last value of VFAS (in fact it will send the last received value for all telemetry values). So if you see VFAS change and then it stays the same value, that could also be because the APM is not sending battery voltage anymore. This I think is your problem. 

The VFAS value if filtered by this project so it won't reach the same value that APM is reporting instantly. It takes a couple of reading to reach a steady value. Your voltage of 3.6V indicates, that perhaps only one value (Mavlink battery message) was received.

I believe the `SR1_EXT_STAT` sends battery voltage, make sure you have that one configured - different from zero!

**Comment by hamshiva** [comment]
Well, thank you very much for your help. I managed to get correct value rasing SR0/1_\* params value to 5. Everything seems good to me.

**Comment by projectkk2glider** [comment]
Cool.
